### ISSUE TITLE
CF stack Rollback 

### ISSUE THREAD

**Issue by maurya-m** [aws-samples/amazon-ec2-gitlab-runner#1]
HI, 
While running the deploy-runner.sh with  desired ami - "ami-0892d3c7ee96c0bf7 " with the other properties, have found the CF gets rollback due to the following error messages: 
```
1. Failed to receive 1 resource signal(s) for the current batch. Each resource signal timeout is counted as a FAILURE. 
2. Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
3.  The following resource(s) failed to create: [RunnerAutoScalingGroup]. Rollback requested by user.

```

Having followed all the pre-requisite in the blog, not able to figure what maybe the issue , Any help here?

Let me know if you needed any additional information in this regards.
Thanks in Advance.

**Comment by qisylvia** [comment]
Hello @maurya-m, 
There could be many causes to why a CFN stack failed to create. To find the root cause, you can start by looking into the CloudFormation stack events log. Use the [CloudFormation console](https://console.aws.amazon.com/cloudformation/) to view the status of your stack. In the console, you can view a list of stack events while your stack is being created, updated, or deleted. From this list, find the failure event and then view the status reason for that event. The status reason might contain an error message from AWS CloudFormation or from a particular service that can help you troubleshoot your problem. For more info on how to troubleshoot CFN problems, please refer to this guide: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html
Hope this helps.

**Comment by maurya-m** [comment]
Thanks for responding here,@
qisylvia

 the issue can be closed, figured out the issue with route table configured on the subnets while setting up the VPC/Subnets.

**Comment by asannikov** [comment]
> Thanks for responding here,@ qisylvia
> 
> the issue can be closed, figured out the issue with route table configured on the subnets while setting up the VPC/Subnets.

@maurya-m what exactly was wrong with route table?
